default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

development:
  <<: *default
  host: 127.0.0.1
  database: cogli_development

test:
  <<: *default
  host: 127.0.0.1
  database: cogli_test

production:
  <<: *default
  database: cogli_production
